venv: 'None'   #  path of virtual environment source or 'None'
screens:
  flow:
    exec: 'flow/flow.py'
    log_dir: 'flow/log'
  ls218:
    exec: 'ls218/temp_218.py'
    log_dir: 'ls218/log'
  adc:
    exec: 'adc/adc_iv.py'
    log_dir: 'adc/log'