pfeiffer-261:
    enable: false
    ip: '192.168.1.108'
    port: '1001'
    timeout: 2
    delay: 5
    indicators:
        - Return_PI
pfeiffer-262:
    enable: false
    ip: '192.168.1.108'
    port: '1002'
    timeout: 2
    delay: 5
    indicators:
        - Supply_PI
si9700:
    enable: false
    ip: '192.168.1.108'
    port: '1003'
    timeout: 2
    delay: 10
    indicators:
        - Heater_HI